"""add age

Revision ID: 12dfd06ea019
Revises: 52b1a424278a
Create Date: 2023-10-17 22:33:30.957995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12dfd06ea019'
down_revision = '52b1a424278a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.alter_column('user', 'image',
               existing_type=sa.BLOB(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.create_index(op.f('ix_user_age'), 'user', ['age'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_age'), table_name='user')
    op.alter_column('user', 'image',
               existing_type=sa.String(length=128),
               type_=sa.BLOB(),
               existing_nullable=True)
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
